//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace expressApp.bdventa
{

    public partial class categoria : XPLiteObject
    {
        int fidcategoria;
        [Key(true)]
        public int idcategoria
        {
            get { return fidcategoria; }
            set { SetPropertyValue<int>(nameof(idcategoria), ref fidcategoria, value); }
        }
        string fdescripcion;
        [Size(45)]
        public string descripcion
        {
            get { return fdescripcion; }
            set { SetPropertyValue<string>(nameof(descripcion), ref fdescripcion, value); }
        }
        [Association(@"productoReferencescategoria")]
        public XPCollection<producto> productoes { get { return GetCollection<producto>(nameof(productoes)); } }
    }

}
