//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace expressApp.bdventa
{

    public partial class cliente : XPLiteObject
    {
        int fidcliente;
        [Key(true)]
        public int idcliente
        {
            get { return fidcliente; }
            set { SetPropertyValue<int>(nameof(idcliente), ref fidcliente, value); }
        }
        string fnombre;
        [Size(45)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fapellido;
        [Size(45)]
        public string apellido
        {
            get { return fapellido; }
            set { SetPropertyValue<string>(nameof(apellido), ref fapellido, value); }
        }
        char fsexo;
        public char sexo
        {
            get { return fsexo; }
            set { SetPropertyValue<char>(nameof(sexo), ref fsexo, value); }
        }
        string fdireccion;
        [Size(80)]
        public string direccion
        {
            get { return fdireccion; }
            set { SetPropertyValue<string>(nameof(direccion), ref fdireccion, value); }
        }
        [Association(@"ventaReferencescliente")]
        public XPCollection<venta> ventas { get { return GetCollection<venta>(nameof(ventas)); } }
    }

}
