//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace expressApp.bdventa
{

    public partial class detalle : XPLiteObject
    {
        int fiddetalle;
        [Key(true)]
        public int iddetalle
        {
            get { return fiddetalle; }
            set { SetPropertyValue<int>(nameof(iddetalle), ref fiddetalle, value); }
        }
        int fcantidad;
        public int cantidad
        {
            get { return fcantidad; }
            set { SetPropertyValue<int>(nameof(cantidad), ref fcantidad, value); }
        }
        float fsubtotal;
        public float subtotal
        {
            get { return fsubtotal; }
            set { SetPropertyValue<float>(nameof(subtotal), ref fsubtotal, value); }
        }
        producto fproducto_idproducto;
        [Association(@"detalleReferencesproducto")]
        public producto producto_idproducto
        {
            get { return fproducto_idproducto; }
            set { SetPropertyValue<producto>(nameof(producto_idproducto), ref fproducto_idproducto, value); }
        }
        venta fventa_idventa;
        [Association(@"detalleReferencesventa")]
        public venta venta_idventa
        {
            get { return fventa_idventa; }
            set { SetPropertyValue<venta>(nameof(venta_idventa), ref fventa_idventa, value); }
        }
    }

}
